version: 2
references:
  container_config: &docker_container_config
    docker:
      - image: docker:17.09.0-ce-git
    working_directory: ~/docker
  container_config: &gitbook_deploy
    docker:
      - image: williamlauze/gitbookdeploy:latest
    working_directory: ~/repo

jobs:
  gitbook_deploy:
    <<: *gitbook_deploy
    steps:
      - checkout
      - run:
          name: gitbook deploy on firebase
          command: |
            sh /scripts/gitbook-build.sh ${GITBOOK_PATH}
            sh /scripts/gitbook-firebase-init.sh ${GITBOOK_PATH}/_book ${GITBOOK_FIREBASE_APP}
            sh /scripts/firebase-deploy-only-hosting.sh gitbook ${GITBOOK_FIREBASE_TOKEN}

workflows:
  version: 2
  build_and_test:
    jobs:
      - gitbook_deploy