version: 2
references:
  container_config: &docker_container_config
    docker:
      - image: docker:17.09.0-ce-git
    working_directory: ~/docker
  container_config: &gitbook_deploy
    docker:
      - image: williamlauze/gitbookdeploy:latest
    working_directory: ~/repo

jobs:
  gitbook_deploy:
    <<: *gitbook_deploy
    steps:
      - checkout
      - run:
          name: gitbook deploy on firebase
          command: |
            jq -n --arg publicpath docs '{"hosting": {"public": "\($publicpath)"}}' > firebase.json
            jq -n '{"projects": {"prod": "harvest-balance-calculator"}}' > .firebaserc
            gitbook build docs
            firebase deploy --only hosting

workflows:
  version: 2
  build_and_test:
    jobs:
      - gitbook_deploy